/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006398",
        "primary-container": "#007bb9",
        "surface-container": "#ffeae1",
        "secondary-container": "#92f5a4",
        "surface": "#fff8f6",
        "background": "#fff8f6",
        "tertiary-container": "#b15f00",
        "error": "#ba1a1a",
        "tertiary": "#8d4b00",
        "surface-bright": "#fff8f6",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-background": "#351000",
        "on-tertiary-fixed": "#2f1500",
        "surface-container-high": "#ffe2d6",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004b73",
        "primary-fixed-dim": "#93ccff",
        "on-secondary-fixed-variant": "#005323",
        "surface-container-low": "#fff1eb",
        "tertiary-fixed": "#ffdcc3",
        "on-primary-container": "#fdfcff",
        "surface-dim": "#ffd0bb",
        "inverse-on-surface": "#ffede6",
        "outline-variant": "#bfc7d2",
        "inverse-surface": "#561f00",
        "on-secondary-container": "#007233",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3f4850",
        "outline": "#707881",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001d31",
        "surface-variant": "#ffdbcc",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#79db8d",
        "primary-fixed": "#cce5ff",
        "secondary-fixed": "#95f8a7",
        "on-surface": "#351000",
        "on-secondary-fixed": "#00210a",
        "on-tertiary-fixed-variant": "#6e3900",
        "primary": "#006194",
        "secondary": "#006d30",
        "surface-container-highest": "#ffdbcc",
        "inverse-primary": "#93ccff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "margin-desktop": "2rem",
        "space-sm": "0.5rem",
        "margin": "1rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-bold": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "800" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "body-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
